CODEIT-FESI-10-5/frontend

- .prettierrc
- next.config.ts
- package-lock.json
- package.json
- src/shared/utils/cn.ts
- svgr.d.ts
- tsconfig.json
Chore: tailwind 관련 패키지 및 svgr 환경 설정
---
- prettier 설정 / prettier-tailwind-plugin 적용
- dayjs 추가
- clsx, tw-merge, cva 패키지 추가
- cn 유틸 함수 추가 (clsx + tw-merge)
- svgr 패키지 추가 및 초기 환경 설정
- public/assets 폴더 생성
---
- svgr를 사용해 svg를 컴포넌트로 쓰는법
```
import IconAdd from '@/public/assets/icon-add.svg';
...
return (
<div>
<IconAdd width={} height={} ... />
</div>
)
```
> Chore/env-setup: tailwind 관련 패키지 및 svgr 환경 설정

- src/app/msw-provider.tsx
-MswProvider가 children을 통해 하위 컴포넌트를 감쌀 수 있도록 수정.
> fix: MswProvider가 children을 받도록 수정

- app/globals.css
- headline, title, body, label 관련 @utility에서 font-family를 'Noto Sans' -> 'Noto Sans KR' 로 변경
- 전체 폰트 사이즈 수정 및 삭제
---
> font 사이즈 변경에 의해 globals.css tailwind 변경

- app/auth/layout.tsx
- app/auth/sign-up/page.tsx
- app/globals.css
- src/features/auth-login/ui/LoginForm.tsx
- src/features/auth-sign-up/model/sign-up.schema.ts
- src/features/get-profile/ui/Profile.tsx
- src/pages/auth/login/LoginPage.tsx
- src/pages/auth/sign-up/SignUpPage.tsx
- src/shared/mocks/handlers.ts
- src/shared/ui/SubmitButton.tsx
- src/widgets/sidebar/ui/SideBarWrapper.tsx
- sidebar wrapper에서 회원가입 경로 오타 수정
- 로그인, 회원가입 스키마 추가 및 입력폼 검증 시점 수정
- todolistHandler 이름 변경 내용 반영해서 수정
- setting 아이콘 위치 수정
- 로그인, 회원가입 스타일 변경
- globals.css disabled 컬러 추가
> chore:사이드바, 로그인, 회원가입 점검

- src/entities/auth/api/index.ts
> chore:signup 이름 수정

- src/features/auth-sign-up/model/index.ts
- src/widgets/sidebar/ui/SideBarWrapper.tsx
> chore:signup 경로 이름 수정

- src/entities/auth/api/requestLogin.ts
- src/features/auth-login/model/useLogin.ts
- src/features/join-study/model/useJoinStudy.ts
- src/features/update-account/ui/InputField.tsx
- src/features/update-account/ui/UpdateName.tsx
- src/features/update-account/ui/UpdatePassword.tsx
- src/features/update-account/ui/UpdateProfile.tsx
- src/pages/account/AccountButton.tsx
> chore: lint error 해결

- src/entities/auth/api/requestSignUp.ts
> fix : 회원가입 api 경로수정

- src/entities/study/api/postCreateStudy.ts
- src/entities/study/model/types.ts
- src/features/create-goal/model/useCreateGoal.ts
- src/features/create-study/model/useCreateStudy.ts
- src/features/create-study/ui/CreateStudyButton.tsx
- src/features/get-goal-list/ui/StudyGoalList.tsx
- src/features/get-study-list/ui/StudyList.tsx
- src/widgets/sidebar/ui/SideBarInfo.tsx
Reverts CODEIT-FESI-10-5/frontend#55
> Revert "chore:사이드바 스터디 생성 및 스터디 리스트 생성 부분 수정"

- src/entities/todolist/api/mock/mocks.ts
- src/entities/todolist/api/mock/todolistHanlders.ts
- src/entities/todolist/lib/utils/divideTodoGroup.ts
- src/widgets/todo/ui/todo.tsx
- src/widgets/todolist-detail/ui/Todolist.tsx
- src/widgets/todolist-detail/ui/TodolistPanel.tsx
todolist-detail -> note 페이지 네비게이션 수정 / Todo없을때 에러 핸들링 추가 
- todo카드에서 note 버튼 Link href 수정
- Todolist에서 투두가 없는경우 표시될 UI추가
- devideTodoGroup에서 빈 배열 전달 받을 경우 map 오류 부분 수정
> fix: todolist-detail -> note 페이지 네비게이션 수정 / Todo없을때 에러 핸들링 추가 

- src/entities/goal/api/postCreateGoal.ts
- src/entities/goal/model/types.ts
- src/features/create-goal/model/useCreateGoal.ts
- src/features/create-study/ui/CreateStudyButton.tsx
- src/features/get-goal-list/ui/StudyGoalList.tsx
> chore:목표 생성 훅 응답 수정

- src/entities/goal/model/types.ts
- src/features/create-goal/model/useCreateGoal.ts
- src/features/create-study/ui/CreateStudyButton.tsx
> chore:route url string으로 수정

- middleware.ts
- src/pages/redirect/RedirectPage.tsx
> chore:로그인 완료시에 redirect페이지로 이동
- 미들웨어에서 대시보드로 이동할경우 redirect로 이동
- 로그인 완료시 redirect로 이동
> chore:로그인 완료시에 redirect페이지로 이동

- src/features/get-goal-list/ui/StudyGoalList.tsx
- src/features/get-note/api/getNote.ts
- src/features/get-note/api/getNoteQueries.ts
- src/pages/note/ui/NoteListPage.tsx
- /note 경로에서 sidebar의 목표 클릭 시, 해당 studyGoalId에 해당하는 노트 목록을 패칭하도록 수정.
> feat: sidebar에서 목표 클릭 시, 노트 목록 렌더링되도룩 수정

- middleware.ts
> chore:middleware api request 수정

- middleware.ts
> chore:로그인 검증 헤더 추가

- middleware.ts
> chore:미들웨어 주석처리
- 중간발표 이후 다시 구현 예정
> chore:미들웨어 주석처리

- src/entities/todolist/api/mock/todolistHanlders.ts
- src/features/update-todo/api/updateTodo.ts
- src/features/update-todo/ui/update-todo.tsx
- src/widgets/todo/ui/todo.tsx
- src/widgets/todolist-detail/ui/TodoCardDragGroup.tsx
- completion checkbox에서 update-todo에 content까지 같이 보내도록 수정 
- priorityOrder index 1부터 시작하도록 수정
> fix: completion checkbox에서 update-todo에 content까지 같이 보내도록 수정 / priorityOrder index 1부터 시작하도록 수정

- src/features/update-study-image/ui/update-study-image.tsx
- src/widgets/goal/ui/goal.tsx
- fix : 노트 모아보기 링크 /note/:goalId -> /note로 변경
- fix : 팀원 달성률 자신 highlight 색상으로 변경
> Feature/fsd dashboard 

- middleware.ts
> chore:middleware fetch부분 수정

- middleware.ts
> chore:응답 실패시 가이드 페이지로 이동

- middleware.ts
- 미들웨어 matcher에 /todolist-detail 경로 추가
> chore:미들웨어 검사 경로에 todolist 추가

- middleware.ts
> chore:미들웨어에 루트 경로 추가

- middleware.ts
> chore:로그인 인증 체크에 루트, 투두리스트 추가
> chore:로그인 인증 체크에 루트, 투두리스트 추가

- src/widgets/sidebar/ui/SideBarNav.tsx
> chore:현재 스터디 가져오기 주석처리 해제

- middleware.ts
> chore:루트 접속시dashboard로 이동

- src/entities/study/api/postCreateStudy.ts
- src/entities/study/api/postJoinStudy.ts
- src/entities/study/model/types.ts
- src/features/create-study/api/handler.ts
- src/features/create-study/model/useCreateStudy.ts
- src/features/create-study/ui/CreateStudyButton.tsx
- src/features/join-study/model/useJoinStudy.ts
- src/widgets/guide/ui/guide.tsx
> chore:스터디 추가시 응답 타입 수정

- app/globals.css
- middleware.ts
- src/entities/dashboard/model/types.ts
- src/entities/study/ui/studyInfo.tsx
- src/pages/dashboard/DashboardPage.tsx
> Feature/mobile font tailwind 모바일용 폰트 추가

- src/features/update-goal-title/ui/update-goal-title.tsx
- dashboard goal title color white로 변경
> style : dashboard goal title color white로 변경

- src/entities/dashboard/model/mocks/mocks.ts
- src/entities/todo/ui/todoInfo.tsx
- src/widgets/goal/ui/goal.tsx
- src/widgets/todo/ui/todo.tsx
> fix : truncate동작 안하는 문제 해결

- src/widgets/guide/ui/guide.tsx
-  description 줄바꿈 로직 변경 및 버튼 변경
---
---
> fix : description 줄바꿈 로직 변경 및 버튼 변경

- app/auth/layout.tsx
- src/features/auth-sign-up/ui/SignUpForm.tsx
- src/pages/auth/login/LoginPage.tsx
- src/pages/auth/sign-up/SignUpPage.tsx
- src/shared/ui/SubmitButton.tsx
> chore:로그인/회원가입 반응형 구현
- 로그인/회원가입 모바일뷰 구현
> chore:로그인/회원가입 반응형 구현

- src/features/create-study/ui/CreateStudyButton.tsx
- src/features/get-goal-list/ui/StudyGoalList.tsx
- src/features/get-profile/ui/Profile.tsx
- src/features/get-study-list/ui/StudyDropDown.tsx
- src/features/join-study/ui/JoinStudyButton.tsx
- src/features/join-study/ui/JoinStudyModal.tsx
- src/features/update-account/ui/UpdateName.tsx
- src/features/update-account/ui/UpdatePassword.tsx
- src/features/update-account/ui/UpdateProfile.tsx
- src/pages/account/AccountPage.tsx
- src/shared/ui/Button.tsx
- src/shared/ui/index.ts
> chore:공통 버튼 생성
- 공통 버튼 생성
- 마이페이지 버튼 변경
- 사이드바 스터디 생성/참여 버튼 변경
- 버튼 생성까지만 한 상태이고, 나머지 페이지들도 변경 예정
> chore:공통 버튼 생성

- src/pages/dashboard/study/[studyId]/goal/[goalId]/goalPage.tsx
- src/widgets/onboarding/ui/onboarding.tsx
- src/widgets/sidebar/ui/SideBarWrapper.tsx
> fix : 전체적인 높이 수정

- src/features/create-goal/api/handler.ts
- src/features/create-goal/model/useCreateGoal.ts
- src/features/create-goal/ui/CreateGoalButton.tsx
- src/features/create-goal/ui/index.ts
- src/features/get-goal-list/ui/StudyGoalList.tsx
> refactor:목표 생성 버튼 분리
- 목표 생성 아이콘 feature/get-goal-list -> feature/create-goal로 분리
> refactor:목표 생성 버튼 분리

- src/features/auth-login/ui/LoginForm.tsx
- src/features/auth-sign-up/ui/SignUpForm.tsx
- src/features/create-study/ui/CreateStudyButton.tsx
- src/features/join-study/ui/JoinStudyButton.tsx
- src/features/join-study/ui/JoinStudyModal.tsx
- src/features/update-account/ui/UpdateName.tsx
- src/features/update-account/ui/UpdatePassword.tsx
- src/features/update-account/ui/UpdateProfile.tsx
- src/shared/ui/Button.tsx
> chore:공통 버튼 수정
- isActive 속성 대신 disabled 사용
- label: 버튼 이름 
- size: 버튼 크기
- theme: 테마(색상)
- className: 추가 클래스 지정 가능
```javascript
<Button
label="스터디 만들기"
size="md"
theme="primary"
className="w-143"
type="button"
disabled={false}
onClick={handleClick}
/>
```
> chore:공통 버튼 수정

- app/auth/layout.tsx
- src/entities/dashboard/model/mocks/dashboardHandlers.ts
- src/entities/dashboard/model/mocks/mocks.ts
- src/entities/todo/ui/todoInfo.tsx
- src/widgets/goal/ui/goal.tsx
- src/widgets/todo/ui/TodoCard.tsx
- fix : teamProgress에서 자신일때 하이라이트 표시 안되는 부분 수정
- fix : todoCard line-clamp-2 적용
-
---
> Fix/dashboard teamProgress 하이라이트 표시, todoCard line-clamp-2 적용

- src/pages/note/ui/NoteListPage.tsx
- 대시보드의 '노트 모아보기' 버튼 클릭 시, 노트 모아보기 페이지 이동 후 목표 목록 중 첫 번째 목표를 자동으로 선택하도록 변경.
- 선택된 목표에 해당하는 노트 목록을 렌더링하도록 변경.
> refator: 노트 모아보기 페이지 접근 시, 첫번째 목표의 노트 목록이 렌더링되도록 수정

- src/features/create-todo/ui/CreateTodoForm.tsx
- src/shared/ui/Button.tsx
Button 공통 컴포넌트 스타일 추가
- Button cursor-pointer 추가
- border-emphasis 색상 추가
- 모바일 글꼴 스타일 추가
> design: Button 공통 컴포넌트 스타일 추가

- app/layout.tsx
- src/app/query-provider.tsx
- src/entities/note/api/noteQueries.ts
- src/pages/note/ui/NoteEditPage.tsx
- src/shared/lib/utils/useCustomMutation.ts
- src/shared/model/useLoadingStore.ts
- src/shared/ui/GlobalLoading.tsx
- src/shared/ui/index.ts
- 전역 로딩 상태 관리 useLoadingStore 훅 생성.
- 빠른 API 응답도 최소 1.5초 로딩 표시 (깜빡임 방지)
- 느린 응답은 실제 시간만큼만 로딩 (불필요한 대기 제거)
```ts
export const useLoadingStore = create<LoadingState>((set) => {
let timeoutId: NodeJS.Timeout | null = null;
let startTime: number | null = null;
return {
isLoading: false,
startLoading: () => {
// 이전 timeout이 있다면 클리어
if (timeoutId) {
clearTimeout(timeoutId);
timeoutId = null;
}
startTime = Date.now();
set({ isLoading: true });
},
stopLoading: () => {
const minLoadingTime = 1500; // 최소 로딩 시간 (1.5초)
const elapsedTime = startTime ? Date.now() - startTime : 0; // 경과 시간 계산
// 경과 시간이 음수, 즉 1.5초 이상 경과하면 0을 반환하여 더 이상 로딩 상태 표시 안함.
// 경과 시간이 양수, 즉 1.5초 미만이면 해당 시간만큼 로딩 상태 표시
const remainingTime = Math.max(0, minLoadingTime - elapsedTime); 
timeoutId = setTimeout(() => {
set({ isLoading: …
```
> feat: mutation 전역 로딩 상태 구현

- app/not-found.tsx
- src/entities/study/ui/studyInfo.tsx
- src/widgets/goal/ui/no-goal.tsx
- src/widgets/guide/ui/guide.tsx
- src/widgets/onboarding/ui/onboarding.tsx
- src/widgets/sidebar/ui/SideBarWrapper.tsx
- src/widgets/study/ui/study.tsx
- guide 공용 버튼으로 변경
- onboarding 공용 버튼으로 변경
- dashboard study 공용 버튼으로 변경
- nogoal 공용 버튼으로 변경
- dashboard, 404 페이지 스크롤 방지
---
> 커스텀 버튼 변경 및 , 스크롤 방지

- src/entities/note/index.ts
- src/entities/todolist/api/mock/todolistHanlders.ts
- src/features/create-todo/ui/ToggleButton.tsx
- src/features/get-study-list/ui/CurrentStudy.tsx
- src/features/update-note/ui/NoteEditorMenu.tsx
- src/shared/ui/Button.tsx
- src/shared/ui/EditorMenuButton.tsx
- src/shared/ui/TextField.tsx
- src/shared/utils/cn.ts
- src/widgets/onboarding/ui/onboarding.tsx
- src/widgets/sidebar/ui/SideBar.tsx
- src/widgets/study/ui/study.tsx
> fix : 빌드 에러 해결 및 cn 중복 함수 삭제

- app/auth/layout.tsx
- src/entities/study/model/queryKeys.ts
- src/features/get-study-list/ui/StudyDropDown.tsx
- src/features/join-study/ui/JoinStudyModal.tsx
- src/widgets/sidebar/ui/SideBarInfo.tsx
- src/widgets/sidebar/ui/SideBarNav.tsx
> chore:ui 오류 수정
- 로그인 페이지 스크롤바 안보이도록 변경
- 로고에 루트 페이지로 이동하는 링크 추가
- study 쿼리키 수정
- 스터디 참여 버튼 disabled 상태 수정
- 스터디 리스트에서 현재 스터디 안보이도록 수정
> chore:ui 오류 수정

- src/entities/note/api/noteApi.ts
- src/entities/note/api/noteHandler.ts
- src/entities/note/api/noteQueries.ts
- src/entities/note/model/mock/notes.mock.ts
- src/entities/note/model/queryKeys.ts
- src/entities/note/model/types.ts
- src/entities/note/ui/NoteItem.tsx
- src/features/get-goal-list/ui/StudyGoalList.tsx
- src/pages/note/ui/NoteEditPage.tsx
- src/pages/note/ui/NoteListPage.tsx
- src/shared/mocks/handlers.ts
- src/widgets/note-list/ui/NoteList.tsx
- NoteListPage, NoteEditPage에 AppBar 적용 및 반응형을 AppBar 반응형에 맞게 수정
- NoteListPage와 NoteEditPage에 line-clamp-2 적용
- studyGoalId를 goalId로 수정
> design: 노트 모아보기 및 노트 작성하기 페이지 AppBar 적용

- middleware.ts
> chore:middleware cache 저장 안하도록 수정
> chore:middleware cache 저장 안하도록 수정

- src/features/create-todo/ui/CreateTodoForm.tsx
- src/shared/ui/CustomToast.tsx
toast 높이 제한 제거, create-todo-form 미입력시 진동 애니메이션 추가
> design: toast 높이 제한 제거, create-todo-form 미입력시 진동 애니메이션 추가

- src/features/delete-goal/ui/deleteGoalButton.tsx
- src/features/delete-study/ui/deleteStudy.tsx
> fix : 모달 mobile 반응형 구현

- src/entities/note/ui/NoteItem.tsx
- NoteItem 제목 색상 text-white 적용
- NoteItem 아이콘 회전 애니메이션 및 노트 접기 애니메이션 수정
> style: 노트 제목 색상 및 애니메이션 수정

- src/widgets/guide/ui/guide.tsx
> chore:guide 페이지 주석 해제

- src/widgets/guide/ui/guide.tsx
> fix : guide 페이지 로딩 로직 수정

- src/features/update-note/ui/NoteEditor.tsx
- src/pages/note/ui/NoteEditPage.tsx
- src/pages/note/ui/NoteListPage.tsx
- src/widgets/note-list/ui/NoteList.tsx
- NoteListPage 및 NoteEditPage에 뒤로가기 버튼 추가.
- NoteEdtor 상태 관련 로직 수정.
> feat: 노트 페이지에 뒤로가기 버튼 추가

- app/redirect/page.tsx
- middleware.ts
- src/entities/study/model/useGetStudy.ts
- src/features/auth-login/model/useLogin.ts
- src/shared/lib/utils/useRedirect.ts
- src/widgets/guide/ui/guide.tsx
> refactor:미들웨어 구조 변경
- 미들웨어에서 root인지 여부에 따라 redirect 경로 다르게 설정
- Guide 페이지를 Root로 변경
- Rediect 페이지 생성
> refactor:미들웨어 구조 변경

- app/page.tsx
- src/pages/guide/guidePage.tsx
- src/pages/guide/index.ts
- src/widgets/guide/ui/guide.tsx
> chore:가이드 페이지 안보이는 문제 해결
- 가이드 페이지 loading 제거
> chore:가이드 페이지 안보이는 문제 해결

- app/redirect/page.tsx
> chore:redirect 코드 수정

- middleware.ts
> chore:middleware config에 루트 경로 추가
> chore:middleware config에 루트 경로 추가

- src/entities/study/ui/studyInfo.tsx
- src/features/delete-study/model/useDeleteStudy.ts
- fix : delete study StudyInfo 쿼리 초기화
> fix : delete study StudyInfo 쿼리 초기화

- src/entities/study/ui/studyInfo.tsx
- src/widgets/study/ui/study.tsx
- 대시보드 햄거버 버튼 sm -< lg 변경
- studyInfo modal 출력 안되는 현상 버그 수정
---
> Dashboar UI 버그 수정

- src/features/auth-login/model/useLogin.ts
> chore:로그인시 스터디, 목표 초기화
- reset store코드 추가
> chore:로그인시 스터디, 목표 초기화
